server:
  port: 8080
  servlet:
    context-path: /api 
logging:
  file: logs/nabeliav4-api.log
      
---

spring:
  profiles: test 
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nabelia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    initialization-mode: always
  # JPA properties
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    use_sql_comments: true
    format_sql: true
  # Logging
  logging:
    level:
      org.springframework: ERROR
      org.hibernate: ERROR